In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
text = ['LONDON PARIS LONDON','PARIS PARIS LONDON']

In [3]:
cv = CountVectorizer()
type(cv)

sklearn.feature_extraction.text.CountVectorizer

In [13]:
count_matrix=cv.fit_transform(text)
print(count_matrix)

  (0, 1)	1
  (0, 0)	2
  (1, 1)	2
  (1, 0)	1


In [5]:
print(count_matrix.toarray())

[[2 1]
 [1 2]]


In [6]:
print(cv.get_feature_names())

['london', 'paris']


In [15]:
print(type(cosine_similarity(count_matrix)))
print(cosine_similarity(count_matrix))

<class 'numpy.ndarray'>
[[1.  0.8]
 [0.8 1. ]]


In [19]:
##Step 1: Read CSV File
movies = pd.read_csv('movie_dataset.csv')
print(movies.columns)

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')


In [23]:
##Step 2: Select Features
movies_df = movies
features = ['keywords','cast','genres','director']
for i in features:
    movies_df[i] = movies_df[i].fillna('')
movies_df.describe()

index        budget             id   popularity       revenue  \
count  4803.000000  4.803000e+03    4803.000000  4803.000000  4.803000e+03   
mean   2401.000000  2.904504e+07   57165.484281    21.492301  8.226064e+07   
std    1386.651002  4.072239e+07   88694.614033    31.816650  1.628571e+08   
min       0.000000  0.000000e+00       5.000000     0.000000  0.000000e+00   
25%    1200.500000  7.900000e+05    9014.500000     4.668070  0.000000e+00   
50%    2401.000000  1.500000e+07   14629.000000    12.921594  1.917000e+07   
75%    3601.500000  4.000000e+07   58610.500000    28.313505  9.291719e+07   
max    4802.000000  3.800000e+08  459488.000000   875.581305  2.787965e+09   

           runtime  vote_average    vote_count  
count  4801.000000   4803.000000   4803.000000  
mean    106.875859      6.092172    690.217989  
std      22.611935      1.194612   1234.585891  
min       0.000000      0.000000      0.000000  
25%      94.000000      5.600000     54.000000  
50%     103.000000      6.200000    235.000000  
75%     118.000000      6.800000    737.000000  
max     338.000000     10.000000  13752.000000

In [27]:
##Step 3: Create a column in DF which combines all selected features
def combine_features(row):
    try:
        return row['keywords'] + " " + row['cast'] + " " + row['genres'] + " " + row['director']
    except:
        print("Error: ",row)
movies_df['combined_features'] = movies.apply(combine_features,axis=1)
print(movies_df['combined_features'].head())

0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combined_features, dtype: object


In [50]:
##Step 4: Create count matrix from this new combined column
cv = CountVectorizer()
type(cv)
count_matrix=cv.fit_transform(movies_df['combined_features'])

In [52]:
#Step5: compute the cosine similarity based on the count_matrix
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.10540926 0.12038585 ... 0.         0.         0.        ]
 [0.10540926 1.         0.0761387  ... 0.03651484 0.         0.        ]
 [0.12038585 0.0761387  1.         ... 0.         0.11145564 0.        ]
 ...
 [0.         0.03651484 0.         ... 1.         0.         0.04264014]
 [0.         0.         0.11145564 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.04264014 0.         1.        ]]


In [45]:
###### helper functions. Use them when needed #######
def get_title_from_index(index):
	return movies_df[movies_df.index == index]["title"].values[0]

def get_index_from_title(title):
	return movies_df[movies_df.title == title]["index"].values[0]
##################################################

In [46]:
movie_user_likes = 'Avatar'
movies_index = get_index_from_title(movie_user_likes)

In [42]:
movies_index

0

In [55]:
similar_movies = list(enumerate(cosine_sim[movies_index]))
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse = True)

In [60]:
sorted_similar_movies

[(0, 1.0000000000000004),
 (94, 0.42339019740572564),
 (2403, 0.3774256780481986),
 (3208, 0.3464101615137755),
 (47, 0.34426518632954817),
 (56, 0.33596842045264647),
 (3158, 0.33333333333333337),
 (2198, 0.31426968052735443),
 (2696, 0.30792014356780045),
 (4401, 0.28867513459481287),
 (1531, 0.2858966759567453),
 (278, 0.2810913475705226),
 (1053, 0.2809003238667948),
 (239, 0.2765204519281134),
 (838, 0.2749859704614352),
 (61, 0.27498597046143514),
 (232, 0.2694301256218254),
 (4332, 0.2694301256218254),
 (661, 0.264197974633739),
 (4593, 0.264197974633739),
 (3730, 0.2592592592592593),
 (1650, 0.2501595914621521),
 (158, 0.24618298195866545),
 (461, 0.24618298195866545),
 (1083, 0.24618298195866542),
 (322, 0.24077170617153845),
 (228, 0.24077170617153842),
 (539, 0.24077170617153842),
 (577, 0.23570226039551587),
 (1990, 0.23570226039551587),
 (1652, 0.23570226039551584),
 (10, 0.23094010767585035),
 (400, 0.23094010767585035),
 (4, 0.23094010767585033),
 (2129, 0.23094010767585

In [62]:
i = 0
for movie in sorted_similar_movies:
    print(get_title_from_index(movie[0]))
    i  =i + 1
    if i > 5:
        break

Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
